// react/src/layouts/AdminLayout/NavBar/NavRight/ChatList/Friends/Friend/index.js
import React from 'react';
import { Card } from 'react-bootstrap';
import { Link } from 'react-router-dom';

const images = require.context('../../../../../../../assets/images/user', true);

const Friend = ({ data, activeId, clicked }) => {
  let photo = images(`./${data.photo}`);
  let timeClass = ['d-block'];
  if (data.status) {
    timeClass = [...timeClass, 'text-c-green'];
  } else {
    timeClass = [...timeClass, 'text-muted'];
  }

  let time = '';
  if (data.time) {
    time = <small className={timeClass.join(' ')}>{data.time}</small>;
  }

  let newFriend = '';
  if (data.new) {
    newFriend = <div className="live-status">{data.new}</div>;
  }

  return (
    <React.Fragment>
      <Card className={activeId === data.id ? 'userlist-box active' : 'userlist-box'} onClick={clicked}>
        <Link to="#" className="media-left">
          {' '}
          <img className="media-object img-radius" src={photo} alt={data.name} />
          {newFriend}
        </Link>
        <Card.Body>
          <h6 className="chat-header">
            {data.name}
            {time}
          </h6>
        </Card.Body>
      </Card>
    </React.Fragment>
  );
};

export default Friend;

// angular/src/app/theme/layout/admin/nav-bar/nav-right/chat-user-list/friend/friend.component.ts
// Angular Import
import { Component, EventEmitter, Input, Output } from '@angular/core';

interface friendsList {
  id: number;
  photo: string;
  name: string;
  new: number;
  status: number;
  time: string;
}

@Component({
  selector: 'app-friend',
  templateUrl: './friend.component.html',
  styleUrls: ['./friend.component.scss']
})
export class FriendComponent {
  @Input() friends!: friendsList;
  @Output() ChatOn = new EventEmitter();

  public innerChatToggle(friends: friendsList) {
    this.ChatOn.emit(friends.id);
  }
}

<div
  class="media userlist-box ripple"
  (click)="innerChatToggle(friends())"
  [attr.data-id]="friends().id"
  [attr.data-status]="{ online: friends().status, offline: !friends().status }"
  [attr.data-username]="friends().name"
>
  <a class="media-left" href="javascript:">
    <img class="media-object img-radius" src="{{ friends().photo }}" alt="{{ friends().name }}" />
    @if (friends().new) {
      <div class="live-status">{{ friends().new }}</div>
    }
  </a>
  <div class="media-body">
    <h6 class="chat-header">
      {{ friends().name }}
      @if (friends().time) {
        <small class="d-block" [ngClass]="{ 'text-c-green': friends().status, 'text-c-red': !friends().status }">
          {{ friends().time }}
        </small>
      }
    </h6>
  </div>
</div>
