// react/src/layouts/AdminLayout/NavBar/NavLeft/NavSearch/index.jsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';

// react-bootstrap
import { Button, FormControl } from 'react-bootstrap';

// ==============================|| NAV SEARCH ||============================== //

const NavSearch = () => {
  const [isOpen, setIsOpen] = useState(false);

  let searchContent = '';
  if (isOpen) {
    searchContent = (
      <div className="search-bar">
        <FormControl type="text" className="border-0 shadow-none" placeholder="Search here" />
        <Button variant="link" type="button" className="close" aria-label="Close" onClick={() => setIsOpen(false)}>
          <span aria-hidden="true">
            <i className="feather icon-x" />
          </span>
        </Button>
      </div>
    );
  }

  return (
    <React.Fragment>
      <Link to="#" className="pop-search" onClick={() => setIsOpen(true)}>
        <i className="feather icon-search" />
      </Link>
      {searchContent}
    </React.Fragment>
  );
};

export default NavSearch;

// angular/src/app/theme/layout/admin/nav-bar/nav-left/nav-search/nav-search.component.ts
// Angular Import
import { Component } from '@angular/core';

@Component({
  selector: 'app-nav-search',
  templateUrl: './nav-search.component.html',
  styleUrls: ['./nav-search.component.scss']
})
export class NavSearchComponent {
  // public props
  searchOn = false;
}

<a href="javascript:void(0)" (click)="this.searchOn = true" class="pop-search" title="Search"><i
    class="feather icon-search"></i></a>
@if (searchOn) {
<div class="search-bar">
  <input type="text" class="form-control border-0 shadow-none" placeholder="Search here" />
  <button (click)="this.searchOn = false" type="button" class="btn-close close" aria-label="Close"></button>
</div>
}
